language: python

python:
  - 2.7
  - 3.5
  - 3.6

addons:
  apt:
    packages:
    - libfuse-dev

install:
  - python setup.py build

script:
  - sudo modprobe fuse
  - mkdir /tmp/foo && python example/hello.py /tmp/foo && [ "$(cat /tmp/foo/hello)" = "Hello World!" ]
  - mkdir /tmp/bar && python example/fioc.py /tmp/bar && [ -f /tmp/bar/fioc ]
